services:
    frontend-singlepage-home:
      container_name: "single-page-restuarant"
      build:
        context: ./single-page/
        dockerfile: Dockerfile.dev
      ports:
        - "3005:3000"
      volumes:
        - ./single-page:/app
        - /app/node_modules
        - ${HOME}/.vscode-server-single-page-restuarant:/home/node/.vscode-server
      command: npm run dev
      networks:
        - main
networks:
  main:
    driver: bridge

volumes:
  postgres-db: