# Build stage
FROM node:22 AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm install next
RUN npm run build

FROM node:22 AS production

WORKDIR /app

COPY --from=build /app ./

EXPOSE 3000

ENV NODE_OPTIONS='--dns-result-order=ipv4first'

CMD ["npm", "run", "start"]
